version: '3'

services:
  bipay_db:
    image: postgres
    environment:
      POSTGRES_DB: bipay_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5555:5432"
  bipay_rest_api:
    build: .
    entrypoint: /rest/docker-entrypoint_last.sh
    volumes:
      - .:/rest
    ports:
      - "8000:8000"
    depends_on:
      - bipay_db
    restart: on-failure

#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - "80:80"
#      - "443:443"
#    restart: on-failure